- type: entity
  id: LockerBoozeFilled
  suffix: Filled
  parent: LockerBooze
  components:
  - type: StorageFill
    contents:
      - id: DrinkShaker
      - id: ClothingEyesHudBeer
      - id: HandLabeler
        amount: 1
      - id: DrinkBottleBeer
        amount: 10
      - id: RagItem
        amount: 1

- type: entity
  id: LockerBartenderFilled
  suffix: Filled
  parent: LockerBartender
  components:
  - type: StorageFill
    contents:
      - id: DrinkShaker
      - id: ClothingEyesHudBeer
      - id: HandLabeler
        amount: 1
      - id: DrinkBottleBeer
        amount: 10
      - id: RagItem
        amount: 1

- type: entity
  id: ClosetChefFilled
  suffix: Filled
  parent: LockerKitchenCloset
  components:
  - type: StorageFill
    contents:
      - id: ReagentContainerFlour
        amount: 3
      - id: ReagentContainerSugar

- type: entity
  id: LockerFreezerMeatFilled
  suffix: Filled
  parent: LockerFreezerMeat
  components:
  - type: StorageFill
    contents:
    - id: FoodMeat
      amount: 4

- type: entity
  id: LockerFreezerFridgeFilled
  suffix: Filled
  parent: LockerFreezerFridge
  components:
  - type: StorageFill
    contents:
    - id: DrinkMilkCarton
      amount: 5
    - id: DrinkSoyMilkCarton
      amount: 5
    - id: FoodContainerEgg
      amount: 2
    - id: FoodMealMint

- type: entity
  id: ClosetJanitorFilled
  suffix: Filled
  parent: ClosetJanitor
  components:
  - type: StorageFill
    contents:
      - id: ClothingUniformJumpsuitJanitor
      - id: FlashlightLantern
      - id: ClothingShoesGaloshes
      - id: ClothingOuterSuitOveralls
      - id: ClothingHandsGlovesColorBlack
      - id: ClothingHeadHatPurplesoft
      - id: WetFloorSign
        amount: 6
      - id: TrashBag
      - id: LightReplacer
      - id: BoxLightMixed
        amount: 2
      - id: Plunger

- type: entity
  id: ClosetLegalFilled
  suffix: Filled
  parent: ClosetLegal
  components:
  - type: StorageFill
    contents:
      - id: ClothingUniformJumpsuitJournalist
      - id: ClothingUniformJumpsuitLawyerBlack
      - id: ClothingUniformJumpsuitLawyerRed
      - id: ClothingUniformJumpsuitLawyerBlue
      - id: ClothingUniformBluesuit
      - id: ClothingUniformPurpsuit
      - id: ClothingShoesColorBlack
      - id: ClothingShoesColorBrown

- type: entity
  id: LockerBotanistFilled
  suffix: Filled
  parent: LockerBotanist
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:GroupSelector
          children:
          - id: ClothingOuterApronBotanist
          - id: ClothingOuterSuitOveralls
        - !type:GroupSelector
          children:
          - id: ClothingBackpackHydroponics
          - id: ClothingBackpackSatchelHydroponics
        - id: ClothingUniformJumpsuitHydroponics
        - id: PlantAnalyzer
        - id: ClothingHeadBandBotany
        - id: HydroponicsToolMiniHoe
        - id: HydroponicsToolHatchet
        - id: ClothingBeltPlant

- type: entity
  id: LockerBotanistLoot
  suffix: Loot
  parent: LockerBotanist
  components:
  - type: StorageFill
    contents:
      - id: ClothingUniformOveralls
      - id: ClothingHeadHatTrucker
        prob: 0.3
      - id: GatfruitSeeds
        prob: 0.1
      - id: FlyAmanitaSeeds
        prob: 0.5
      - id: NettleSeeds
        prob: 0.7

- type: entity
  id: ClosetJanitorBombFilled
  parent: ClosetJanitorBomb
  suffix: Filled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetJanitorBombSuit
      - id: ClothingOuterSuitJanitorBomb
